# Generated by Django 2.1.5 on 2022-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=90, blank=True)),
                ('email_text', models.CharField(max_length=62, blank=True)),
                ('coordinates_text', models.CharField(max_length=40, blank=True)),
                ('phenotypes_text', models.CharField(max_length=300, blank=True)),
                ('comments_text', models.CharField(max_length=600, blank=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
