# Generated by Django 3.2.9 on 2022-03-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0002_auto_20220202_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='comments_text',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='coordinates_text',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='phenotypes_text',
            new_name='phenotypes',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='pub_date',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='email_text',
            new_name='submitter_email',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='name_text',
            new_name='submitter_name',
        ),
    ]
