# Generated by Django 3.2.9 on 2022-04-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0003_auto_20220302_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
