from api.views.chromosome import ChromosomeViewSet
from api.views.gene import GeneViewSet
from api.views.hpo import HPOViewSet
from api.views.tad import TADViewSet
from api.views.enhancer import EnhancerViewSet
from api.views.track import TrackViewSet
from api.views.element import ElementViewSet 
from api.views.ut import UTViewSet 
from api.views.variant import VariantViewSet 
