# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180418_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1)),
                ('length', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=-1)),
                ('end', models.IntegerField(default=-1)),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='HPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpoid', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=500)),
                ('definition', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='hpos',
            field=models.ManyToManyField(to='home.HPO'),
        ),
    ]
