# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180925_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hpo',
            name='weight',
            field=models.FloatField(default=-1),
        ),
    ]
