# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hpo_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(default=-1)),
                ('right', models.IntegerField(default=-1)),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Chromosome')),
            ],
        ),
    ]
