# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-20 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=-1)),
                ('end', models.IntegerField(default=-1)),
                ('vista_element', models.IntegerField(default=-1)),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Chromosome')),
            ],
        ),
    ]
