# Generated by Django 2.1.4 on 2018-12-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_enhancer'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
