# Generated by Django 2.1.4 on 2018-12-13 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20181212_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=-1)),
                ('end', models.IntegerField(default=-1, null=True)),
                ('details', models.CharField(default='', max_length=2000)),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.IntegerField(default=-1)),
                ('label', models.CharField(default='', max_length=200)),
                ('build', models.CharField(default='', max_length=30)),
                ('track_type', models.CharField(default='', max_length=100)),
                ('details', models.CharField(default='', max_length=2000)),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Track'),
        ),
    ]
