# Generated by Django 2.1.4 on 2018-12-13 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181213_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='subscribers',
            field=models.ManyToManyField(related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
