# Generated by Django 2.1.4 on 2018-12-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181214_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tad',
            old_name='right',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='tad',
            old_name='left',
            new_name='start',
        ),
    ]
