# Generated by Django 2.1.4 on 2018-12-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181214_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='ut',
            name='color',
            field=models.CharField(default='#0000FF', max_length=20),
        ),
    ]
