# Generated by Django 2.1.4 on 2018-12-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_element_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromosome',
            name='number',
            field=models.CharField(default='', max_length=2),
        ),
    ]
