# Generated by Django 2.1.4 on 2018-12-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181220_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpo',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='hpo',
            name='definition',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='study',
            field=models.CharField(default='', max_length=300),
        ),
    ]
