# Generated by Django 2.1.4 on 2018-12-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20181220_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpo',
            name='comment',
            field=models.CharField(default='', max_length=2100),
        ),
        migrations.AlterField(
            model_name='hpo',
            name='definition',
            field=models.CharField(default='', max_length=2100),
        ),
    ]
