# Generated by Django 2.1.4 on 2020-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20181220_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim_number', models.IntegerField(default=-1)),
                ('title', models.CharField(default='', max_length=500)),
                ('dominant', models.BooleanField(default=False)),
                ('recessive', models.BooleanField(default=False)),
                ('hpos', models.ManyToManyField(to='home.HPO')),
            ],
        ),
    ]
