# Generated by Django 2.1.4 on 2020-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_omim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omim',
            old_name='dominant',
            new_name='autosomal_dominant',
        ),
        migrations.RenameField(
            model_name='omim',
            old_name='recessive',
            new_name='autosomal_recessive',
        ),
        migrations.AddField(
            model_name='omim',
            name='mitochondrial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omim',
            name='x_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omim',
            name='x_linked_dominant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omim',
            name='x_linked_recessive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omim',
            name='y_linked',
            field=models.BooleanField(default=False),
        ),
    ]
