# Generated by Django 2.1.4 on 2020-04-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200403_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='omim',
            name='multifactorial',
            field=models.BooleanField(default=False),
        ),
    ]
