# Generated by Django 2.1.4 on 2020-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_omim_multifactorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omim',
            name='digenic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omim',
            name='digenic_dominant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omim',
            name='digenic_recessive',
            field=models.BooleanField(default=False),
        ),
    ]
