# Generated by Django 2.1.4 on 2020-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200403_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omim',
            name='hpos',
            field=models.ManyToManyField(related_name='omims', to='home.HPO'),
        ),
    ]
