# Generated by Django 2.1.4 on 2020-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200409_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='symbols',
            field=models.IntegerField(default=0),
        ),
    ]
