# Generated by Django 2.1.4 on 2020-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_gene_ensembl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='omims',
            field=models.ManyToManyField(to='home.Omim'),
        ),
    ]
