# Generated by Django 2.1.4 on 2020-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20200413_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='', max_length=100)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
