# Generated by Django 2.1.4 on 2022-01-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_singleviewer'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='variant',
        #     name='gains',
        # ),
        # migrations.RemoveField(
        #     model_name='variant',
        #     name='losses',
        # ),
    ]
