# Generated by Django 3.2.9 on 2022-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220330_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='creator_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
