# Generated by Django 3.2.9 on 2022-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_track_creator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
