# Generated by Django 3.2.9 on 2022-03-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
    ]
