# Generated by Django 3.2.9 on 2022-03-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_chromosome_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
    ]
