# Generated by Django 3.2.9 on 2022-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_gene_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
