# Generated by Django 3.2.9 on 2022-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_gene_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default='', max_length=600)),
                ('coordinates', models.CharField(max_length=40)),
                ('phenotypes', models.CharField(blank=True, default='', max_length=300)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submitter_email', models.CharField(max_length=62)),
                ('submitter_name', models.CharField(max_length=90)),
            ],
        ),
    ]
