# Generated by Django 3.2.9 on 2022-04-04 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(default='Pending Review', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='case',
            name='phenotypes',
        ),
        migrations.AddField(
            model_name='case',
            name='phenotypes',
            field=models.ManyToManyField(to='home.HPO'),
        ),
    ]
