# Generated by Django 3.2.9 on 2022-04-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220404_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='builds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
    ]
