# Generated by Django 3.2.9 on 2022-04-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_case_builds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='builds',
            new_name='build',
        ),
    ]
