# Generated by Django 3.2.9 on 2022-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rename_builds_case_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='evidence',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='submitter_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='submitter_name',
            field=models.CharField(max_length=100),
        ),
    ]
