# Generated by Django 3.2.9 on 2022-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20220404_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pubmed_ids',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
