# Generated by Django 3.2.9 on 2022-04-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_case_pubmed_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='phenotypes_text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
