# Generated by Django 3.2.9 on 2022-04-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_case_phenotypes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
        migrations.AddField(
            model_name='enhancer',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
        migrations.AddField(
            model_name='tad',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
        migrations.AddField(
            model_name='tad',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.track'),
        ),
    ]
