# Generated by Django 3.2.9 on 2022-04-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20220405_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='build',
        ),
    ]
