# Generated by Django 3.2.9 on 2022-04-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_track_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.build'),
        ),
    ]
