# Generated by Django 3.2.9 on 2022-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_track_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
