# Generated by Django 3.2.9 on 2022-05-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20220405_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancer',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enhancers', to='home.track'),
        ),
        migrations.AlterField(
            model_name='tad',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tads', to='home.track'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='home.track'),
        ),
    ]
