# Generated by Django 3.2.9 on 2022-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20220501_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='long_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
