# Generated by Django 3.2.16 on 2023-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_track_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='author_last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='doi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='pubmed_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
