# Generated by Django 3.2.16 on 2023-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20230403_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='evidence',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
