# Generated by Django 3.2.16 on 2023-05-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_case_evidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hpo',
            old_name='hpoid',
            new_name='hpo_id',
        ),
    ]
