# Generated by Django 2.1.4 on 2018-12-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181215_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmanager',
            name='default_enhancers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackmanager',
            name='default_tads',
            field=models.BooleanField(default=True),
        ),
    ]
