# Generated by Django 2.1.4 on 2018-12-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_trackmanager_default_cnvs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed',
            new_name='is_active',
        ),
    ]
