# Generated by Django 2.1.4 on 2022-01-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181226_0757'),
        ('user', '0006_user_token'),
    ]

    operations = [
    ]
