# Generated by Django 3.2.9 on 2022-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
